package CSCI5308.GroupFormationTool.SecurityTest;

import CSCI5308.GroupFormationTool.Security.IPasswordEncryption;
import CSCI5308.GroupFormationTool.Security.IPasswordPolicyPersistence;
import CSCI5308.GroupFormationTool.Security.IUserPasswordRelationshipPersistence;

public interface ISecurityAbstractFactoryTest {

	IPasswordPolicyPersistence returnPasswordPolicyDBMock();
	IUserPasswordRelationshipPersistence returnUserPasswordRelationshipDBMock();
	IPasswordEncryption returnPasswordEncryptionMock();
}
